[ua]
languageName = "Україньска"
contentdir = "content/ua"
weight = 1

[ru]
languageName = "Русский"
contentdir = "content/ru"
weight = 2

[cs]
languageName = "Čeština"
contentdir = "content/cs"
weight = 3