[ua]
languageName = "Українська"
contentDir = "content/ua"
weight = 25
[ua.params]
    languageISO = "ua"
    titleAddition = "Інформація для громадян України в Чехії у зв'язку з конфліктом в Україні"
    description = "Інформація для громадян України в Чехії у зв'язку з конфліктом в Україні"
    titleHome = "Інфо"
    footer = "© 2022 <a href=\"https://itforspace.com/\">ITforSpace </a> s.r.o. Powered by <a href=\"https://getdoks.org/\">Doks</a>"

[ru]
languageName = "Русский"
contentDir = "content/ru"
weight = 25
[ru.params]
    languageISO = "ru"
    titleAddition = "Информация для граждан Украины пребывающих в Чехии"
    description = "Информация для граждан Украины пребывающих в Чехии"
    titleHome = "Інфо"
    footer = "© 2022 <a href=\"https://itforspace.com/\">ITforSpace </a> s.r.o. Powered by <a href=\"https://getdoks.org/\">Doks</a>"
