name = "Ukrajinec.cz"
license = "MIT"
licenselink = "https://github.com/h-enk/doks/blob/master/LICENSE"
description = "Web page to hold basic helpful information to ukrainian refugies coming to Czechia"

homepage = "https://github.com/h-enk/doks-child-theme"
demosite = "https://doks-child-theme.netlify.app"

tags = ["uprhclici", "ukrajinci prace", "ukrajinici ubytovani", "pomoc uprchlikum", "українці", "чехія", "бєженці"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "dark mode"]

[author]
  name = "IT for Space"
  homepage = "https://ukrajinec.cz"
